/**
 * Typed access to the verified aggregate JSON behind the Findings page's Analysis tab.
 *
 * public/data/findings/*.json is generated by scripts/export_findings_data.py from
 * data/processed/analysis/*.csv (never respondent-level data). The broader-group
 * MF-holding-share context and per-field coverage/routing-evidence tables are
 * deliberately NOT duplicated here — they're reused directly from
 * public/data/dataset-method/{sample_selection,coverage}.json, already generated for
 * the Dataset and Method page, per instructions to treat existing exports as the
 * source of truth rather than re-deriving them.
 */
import barriersData from "../../public/data/findings/barriers.json"
import encouragementData from "../../public/data/findings/encouragement.json"
import comparisonByExperienceData from "../../public/data/findings/comparison_by_experience.json"
import comparisonByIncomeData from "../../public/data/findings/comparison_by_income.json"
import demographicsData from "../../public/data/findings/demographics.json"

export interface BarrierField {
  field_code: string
  question_wording: string
  denominator: number
  focused_group_size: number
  intended_respondent_group: string
  routing_evidence: string
  options: { option: string; n: number; pct_of_answered: number }[]
}

export interface ComparisonByExperience {
  note: string
  group_sizes: Record<string, number>
  barriers_AA2_DD2: Record<string, string | number | null>[]
  encouragement_AA3_DD3: Record<string, string | number | null>[]
}

export interface ComparisonByIncome {
  note: string
  tier_sizes: { income_tier: string; n: number }[]
  coverage: { group: string; n_group: number; n_answered: number; coverage_pct: number; meets_small_group_min: boolean }[]
  barriers_AA2_DD2: Record<string, string | number | null>[]
}

export interface DemographicField {
  field_code: string
  label: string
  question_wording: string
  group: "Demographics" | "Psychographics"
  denominator: number
  n_answered: number
  n_blank: number
  options: { label: string; n: number; pct: number }[]
}

export interface Demographics {
  focused_group_size: number
  note: string
  fields: DemographicField[]
}

export const barriers = barriersData as BarrierField
export const encouragement = encouragementData as BarrierField
export const comparisonByExperience = comparisonByExperienceData as ComparisonByExperience
export const comparisonByIncome = comparisonByIncomeData as ComparisonByIncome
export const demographics = demographicsData as Demographics
