/**
 * Typed access to the "Who is in our sample?" tab's data.
 *
 * public/data/findings/who_is_in_sample.json is the aggregate-only, unfiltered
 * (n = 553) baseline generated by scripts/export_who_is_in_sample.py — safe for
 * production. Combined-filter results (state × urban/rural × income tier ×
 * previous-investment experience) are only ever computed by the dev-only route
 * src/app/api/dev/who-is-in-sample/route.ts, which returns data shaped
 * identically to this baseline so the tab can render either one the same way.
 */
import baseData from "../../public/data/findings/who_is_in_sample.json"
import indiaMap from "@svg-maps/india"

export interface FieldOption {
  label: string
  n: number
  pct: number
}

export interface WhoField {
  field_code: string
  label: string
  question_wording: string
  section: "geography" | "work_household" | "preferences" | "knowledge"
  kind: "single" | "multi"
  denominator: number
  n_answered: number
  n_blank: number
  options: FieldOption[]
}

export interface KnowledgeItem {
  field_code: string
  label: string
  n_answered: number
  n_blank: number
  options: FieldOption[]
}

export interface WhoIsInSampleData {
  focused_group_size: number
  note: string
  sample_overview: {
    n: number
    age_band: string
    occupation_scope: string
    research_scope: string
  }
  filter_options: {
    income_tier: { tier: string; n: number }[]
    prev_mf_investment_class: { cls: string; n: number }[]
    urbanrural: { value: string; n: number }[]
  }
  state_urbanrural_crosstab: { state: string; urban_n: number; rural_n: number }[]
  fields: WhoField[]
  knowledge_grid: {
    field_family: string
    note: string
    items: KnowledgeItem[]
  }
  matched_n?: number
}

export const whoIsInSampleBase = baseData as WhoIsInSampleData

export const PREV_INVESTMENT_LABEL: Record<string, string> = {
  past_mf_investor: "Past MF investor",
  explicit_no_prior_investment: "None of the 7 listed products",
  past_investor_other_product_only: "Other product only (not MF)",
}

export const PREV_INVESTMENT_ORDER = [
  "past_mf_investor",
  "explicit_no_prior_investment",
  "past_investor_other_product_only",
]

export const INCOME_TIER_ORDER = [
  "Up to Rs.20,000",
  "Rs.20,001-Rs.40,000",
  "Above Rs.40,000",
  "Do not wish to disclose",
  "No current income",
]

export const INCOME_BRACKET_ORDER = [
  "Upto Rs. 5,000",
  "Rs. 5,001 – Rs. 10,000",
  "Rs.10,001 – Rs. 15,000",
  "Rs.15,001 – Rs. 20,000",
  "Rs.20,001 – Rs. 30,000",
  "Rs.30,001 – Rs. 40,000",
  "Rs.40,001 – Rs. 50,000",
  "Rs.50,001 – Rs. 60,000",
  "Rs.60,001 – Rs. 80,000",
  "Rs.80,001 – Rs. 1,00,000",
  "Rs.1,00,001 – Rs. 1,25,000",
  "Rs.1,25,001 – Rs. 3,00,000",
  "Rs.3,00,001 - Rs. 5,00,000",
  "More than Rs. 5,00,000",
  "Do not wish to disclose",
  "No current income",
]

// Reputable, documented boundary source: @svg-maps/india (CC-BY-4.0), the
// widely-used svg-maps project's India states/UTs layer — 36 locations, no
// hand-drawn approximation. https://www.npmjs.com/package/@svg-maps/india
export interface IndiaLocation {
  id: string
  name: string
  path: string
}

export const INDIA_MAP = indiaMap as unknown as {
  label: string
  viewBox: string
  locations: IndiaLocation[]
}

// SELECTED_STATE (this survey's own spelling/casing) -> @svg-maps/india id.
// Verified manually against the full 36-location list shipped by the package —
// every one of the 31 distinct SELECTED_STATE values observed in the 553-
// respondent focused group resolves to exactly one id below. The remaining 5
// ids (dn, ld, mn, ml, tr) have zero respondents in this sample but are still
// valid geography — rendered as zero, not "unavailable."
export const STATE_KEY_TO_SVG_ID: Record<string, string> = {
  "ANDAMAN & NICOBAR ISLANDS": "an",
  "ANDHRA PRADESH": "ap",
  "ARUNACHAL PRADESH": "ar",
  ASSAM: "as",
  BIHAR: "br",
  CHANDIGARH: "ch",
  CHHATTISGARH: "ct",
  "DAMAN & DIU": "dd",
  "NCT OF DELHI": "dl",
  GOA: "ga",
  GUJARAT: "gj",
  HARYANA: "hr",
  "HIMACHAL PRADESH": "hp",
  "JAMMU & KASHMIR": "jk",
  JHARKHAND: "jh",
  KARNATAKA: "ka",
  KERALA: "kl",
  "MADHYA PRADESH": "mp",
  MAHARASHTRA: "mh",
  MIZORAM: "mz",
  NAGALAND: "nl",
  ODISHA: "or",
  PUDUCHERRY: "py",
  PUNJAB: "pb",
  RAJASTHAN: "rj",
  SIKKIM: "sk",
  "TAMIL NADU": "tn",
  TELANGANA: "tg",
  "UTTAR PRADESH": "up",
  UTTARAKHAND: "ut",
  "WEST BENGAL": "wb",
}

export function formatN(n: number): string {
  return n.toLocaleString("en-IN")
}

export type Zone = "NORTH" | "SOUTH" | "EAST" | "WEST"

// SELECTED_STATE -> Zone_DP, as SEBI itself classifies it (not this study's own
// grouping). Verified directly against the raw workbook: every one of these 30
// states/UTs maps to exactly one zone across all 553 focused-group respondents
// (0 states span more than one zone in the data).
export const STATE_TO_ZONE: Record<string, Zone> = {
  "ANDAMAN & NICOBAR ISLANDS": "EAST",
  "ANDHRA PRADESH": "SOUTH",
  "ARUNACHAL PRADESH": "EAST",
  ASSAM: "EAST",
  BIHAR: "EAST",
  CHANDIGARH: "NORTH",
  CHHATTISGARH: "WEST",
  "DAMAN & DIU": "WEST",
  "NCT OF DELHI": "NORTH",
  GOA: "WEST",
  GUJARAT: "WEST",
  HARYANA: "NORTH",
  "HIMACHAL PRADESH": "NORTH",
  "JAMMU & KASHMIR": "NORTH",
  JHARKHAND: "EAST",
  KARNATAKA: "SOUTH",
  KERALA: "SOUTH",
  "MADHYA PRADESH": "WEST",
  MAHARASHTRA: "WEST",
  MIZORAM: "EAST",
  NAGALAND: "EAST",
  ODISHA: "EAST",
  PUDUCHERRY: "SOUTH",
  PUNJAB: "NORTH",
  RAJASTHAN: "WEST",
  SIKKIM: "EAST",
  "TAMIL NADU": "SOUTH",
  TELANGANA: "SOUTH",
  "UTTAR PRADESH": "NORTH",
  UTTARAKHAND: "NORTH",
  "WEST BENGAL": "EAST",
}

export const ZONE_LABELS: Record<Zone, string> = {
  NORTH: "North",
  SOUTH: "South",
  EAST: "East",
  WEST: "West",
}
